const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE :'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS :'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin 
    // // get user property creating form 
    GET_GENDER_START:'GET_GENDER_START',
    GET_GENDER_SUCCESS:'GET_GENDER_SUCCESS',
    GET_GENDER_FAIL:'GET_GENDER_FAIL',

    GET_POSITION_SUCCESS:'GET_POSITION_SUCCESS',
    GET_POSITION_FAIL:'GET_POSITION_FAIL',

    GET_ROLE_SUCCESS:'GET_ROLE_SUCCESS',
    GET_ROLE_FAIL:'GET_ROLE_FAIL',
    // // CRUD user 
    SAVE_USER_SUCCESS:'SAVE_USER_SUCCESS',
    SAVE_USER_FAIL:'SAVE_USER_FAIL',

    DELETE_USER_SUCCESS:'DELETE_USER_SUCCESS',
    DELETE_USER_FAIL:'DELETE_USER_FAIL',
    
    EDIT_USER_SUCCESS:'EDIT_USER_SUCCESS',
    EDIT_USER_FAIL:'EDIT_USER_FAIL',

    FETCH_ALL_USER_SUCCESS :'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAIL:'FETCH_ALL_USER_FAIL',

    FETCH_TOP_DOCTORS_SUCCESS:'FETCH_TOP_DOCTORS_SUCCESS',
    FETCH_TOP_DOCTORS_FAIL:'FETCH_TOP_DOCTORS_FAIL',

    FETCH_ALL_DOCTORS_SUCCESS:'FETCH_ALL_DOCTORS_SUCCESS',
    FETCH_ALL_DOCTORS_FAIL:'FETCH_ALL_DOCTORS_FAIL',

    SAVE_DETAIL_DOCTOR_SUCCESS:'SAVE_DETAIL_DOCTOR_SUCCESS',
    SAVE_DETAIL_DOCTOR_FAIL:'SAVE_DETAIL_DOCTOR_FAIL',

    FETCH_ALL_SCHEDULE_TIME_SUCCESS:'FETCH_ALL_SCHEDULE_TIME_SUCCESS',
    FETCH_ALL_SCHEDULE_TIME_FAIL:'FETCH_ALL_SCHEDULE_TIME_FAIL',

    FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS:'FETCH_REQUIRED_DOCTOR_INFOR_SUCCESS',
    FETCH_REQUIRED_DOCTOR_INFOR_FAIL:'FETCH_REQUIRED_DOCTOR_INFOR_FAIL'
})

export default actionTypes;